services:
  app:
    environment:
      OTEL_ENABLED: "true"
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: http://otel-collector:4318/v1/traces
    networks:
      - spring-network
      - templates-observability

networks:
  spring-network:
    driver: bridge
  templates-observability:
    external: true
