FROM maven:3.9-eclipse-temurin-25-alpine@sha256:21e373f51c0b14c9c76d415033f4eb145d1c0b59cd227a3ec5cc1c78002c6da8

WORKDIR /app

# Cache dependencies first
COPY pom.xml ./
RUN mvn -B dependency:go-offline

COPY . .

EXPOSE 3000

CMD ["mvn", "-q", "spring-boot:run", "-Dspring-boot.run.jvmArguments=--enable-native-access=ALL-UNNAMED --sun-misc-unsafe-memory-access=allow -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
