FROM maven:3.9-eclipse-temurin-21-alpine

WORKDIR /app

# Cache dependencies first
COPY pom.xml ./
RUN mvn -B dependency:go-offline

COPY . .

EXPOSE 3000

CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]
